---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
  - type: heading
    label: Menu
  - type: directory
    path: markdowns/menu
    label: Master List Menu Items
    create: all
    match: "*.md"
    templates:
    - menu-item
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  instant_preview_command: npm run dev
