---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
  - type: heading
    label: Menu
  - type: directory
    path: markdowns/menu
    label: Master List Menu Items
    create: documents
    match: "*.md"
    templates:
    - menu-item.yml
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"