---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
  - type: heading
    label: Home Page
  - type: directory
    path: markdowns/home
    label: Intro Content
    create: documents
    match: "*.md"
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"